// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ew0s/ewos-to-go-hw/http5/homework/chat-server/internal/service/user (interfaces: Hasher)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthHasher is a mock of Hasher interface.
type MockUserHasher struct {
	ctrl     *gomock.Controller
	recorder *MockUserHasherMockRecorder
}

// MockAuthHasherMockRecorder is the mock recorder for MockAuthHasher.
type MockUserHasherMockRecorder struct {
	mock *MockUserHasher
}

// NewMockAuthHasher creates a new mock instance.
func NewMockUserHasher(ctrl *gomock.Controller) *MockUserHasher {
	mock := &MockUserHasher{ctrl: ctrl}
	mock.recorder = &MockUserHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserHasher) EXPECT() *MockUserHasherMockRecorder {
	return m.recorder
}

// GenerateFromPassword mocks base method.
func (m *MockUserHasher) GenerateFromPassword(arg0 []byte, arg1 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFromPassword", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateFromPassword indicates an expected call of GenerateFromPassword.
func (mr *MockUserHasherMockRecorder) GenerateFromPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFromPassword", reflect.TypeOf((*MockUserHasher)(nil).GenerateFromPassword), arg0, arg1)
}
